let profile_data = [
    {id: 0,
     draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/circle-500.jpg",
     icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/circle.png" },
    {id: 1,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/square-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/square.png" },
    {id: 2,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/plate-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/plate.png" },
    {id: 3,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/profile-circle-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/profile-circle.png" },
    {id: 4,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/profile-square-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/profile-square.png" },
    {id: 5,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/channel-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/channel.png" },
    {id: 6,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/hexahedron-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/hexahedron.png" },
    {id: 7,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/bead-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/bead.png" },
    {id: 8,
        draw_src : "/files/static/core/imgs/calculator/calc-img-measure-500/corner-500.jpg",
        icon_src : "/files/static/core/imgs/calculator/calc-img-measure-40/corner.png" },
]

export default profile_data
